### PR TITLE
feat: Support Valkey

### PR DESCRIPTION
**Pull request by magreenbaum**
## Description
Support Valkey. 

As a note, there is a [bug in the provider](https://github.com/hashicorp/terraform-provider-aws/issues/39905) where `aws_elasticache_cluster` doesn't support Valkey.

## Motivation and Context
Closes: https://github.com/terraform-aws-modules/terraform-aws-elasticache/issues/25
https://github.com/hashicorp/terraform-provider-aws/pull/39972

## Breaking Changes
No.

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by bryantbiggs** [comment]
we should wait for the upstream provider bug to be resolved first, no?

**Comment by magreenbaum** [comment]
> we should wait for the upstream provider bug to be resolved first, no?

@bryantbiggs we can, but I figured this way those that want to use valkey for replication groups and serverless can do so in the mean time.

**Comment by phene** [comment]
Awesome. Please lets merge this regardless of the provider bug.

**Comment by bryantbiggs** [comment]
I've pinged a few folks - I don't want to add support for something that is known to not work

**Comment by bryantbiggs** [comment]
FYI - https://github.com/hashicorp/terraform-provider-aws/pull/39972#issuecomment-2474848288

So we shouldn't add support for it here for cache clusters (serverless and replication groups do support it and we can support that as well)

**Comment by magreenbaum** [comment]
Added a conditional to not create clusters if engine is `valkey`.

**Comment by eahangari-8x8** [comment]
Hi All, any update on Valkey support?

**Comment by bryantbiggs** [comment]
I will take a look today - it's re:Invent season plus the holiday season so be patient 😅

**Review by bryantbiggs — APPROVED** [review]
thank you @magreenbaum, another  phenomenal contribution 🎉

**Comment by antonbabenko** [comment]
This PR is included in version 1.4.0 :tada:

**Comment by taer** [comment]
This line seems to prevent valkey creation still
https://github.com/terraform-aws-modules/terraform-aws-elasticache/blob/master/main.tf#L8
```
  # elasticache clusters currently do not support engine type valkey
  # TODO: remove this local `create_cluster` conditional once this bug is addressed:
  # https://github.com/hashicorp/terraform-provider-aws/issues/39905
  create_cluster = var.create_cluster && var.engine != "valkey" ? true : false
```

when I put valkey in for the engine with the latest module, I get a delete of my cluster. Should this above line vanish now? @magreenbaum

**Comment by bryantbiggs** [comment]
Valkey is not supported on clusters, only replication groups

**Pull request merged**
